import Link from 'next/link'
import { marketingMetadata } from '@/lib/marketing/seo'
import { Breadcrumbs } from '../../_components/breadcrumbs'
import { DocumentTemplate } from '../document-template'

export const metadata = marketingMetadata({ title: 'Free HVAC Invoice Template — Print or Save PDF', description: 'Create an itemized HVAC invoice with customer details, labor, materials, tax and payment notes. Free printable template. No signup or email required.', path: '/resources/hvac-invoice-template' })

export default function InvoiceTemplatePage() {
  return <main id="marketing-content" tabIndex={-1} className="section shell">
    <Breadcrumbs items={[{ name: 'Home', path: '/' }, { name: 'Resources', path: '/resources' }, { name: 'HVAC invoice template', path: '/resources/hvac-invoice-template' }]} />
    <header className="page-heading"><p className="eyebrow">Free printable template</p><h1>An HVAC invoice<br />with the details in place.</h1><p>Record the work, itemize the charges and make the amount due clear. Fill out this invoice in your browser, then print it or save a PDF. No account required.</p></header>
    <DocumentTemplate kind="invoice" />
    <div className="resource-editorial"><section><h2>What belongs on an HVAC service invoice?</h2><p>A useful invoice lets the customer connect a charge to a particular visit. Give it a unique number, add your business contact details, and identify the customer and service address separately if they differ.</p><ol><li><strong>Visit and equipment:</strong> include the date of service, work reference and relevant equipment model or serial number.</li><li><strong>Work completed:</strong> describe the diagnosis, approved repair and any testing performed. Separate completed work from future recommendations.</li><li><strong>Itemized charges:</strong> list labor, parts and fees with quantities and unit prices. Use descriptions a customer can understand.</li><li><strong>Total and timing:</strong> check the subtotal and applicable tax, state the payment due date, and include the payment methods you actually accept.</li><li><strong>Follow-up details:</strong> add the job-specific warranty or workmanship terms and a contact for questions.</li></ol><p>The template does not decide which charges are taxable or supply your contract terms. Use the rules and terms applicable to your business and the job.</p></section>
    <section><h2>A worked example</h2><p>A sample repair might include a $95 diagnostic visit, an $85 replacement part and 1.5 hours of labor at $90 per hour. The subtotal is $315 before tax. These numbers demonstrate the calculation; they are not suggested prices for your market.</p><p>Select “Load example” above to see the line items. Replace every sample detail and confirm your actual charges before sharing the document.</p></section>
    <section><h2>Invoice or estimate?</h2><p>An estimate describes proposed work and expected pricing for approval. An invoice records the amount billed for work. If the scope has not been accepted yet, start with the <Link href="/resources/hvac-estimate-template">HVAC estimate template</Link>. If the completed work differs from the approved scope, document the change before billing it.</p></section>
    <section><h2>When is a template enough?</h2><p>A standalone PDF can work when you have a small number of jobs and a dependable way to track document numbers, revisions and payment status. It does not send the invoice, collect money, update customer records or confirm a payment.</p><p>As your workload grows, <Link href="/hvac-invoicing-software">FieldClose’s HVAC invoicing workflow</Link> keeps the invoice connected to the customer, job and approved estimate. A connected Stripe account provides customer checkout; payment status follows verified payment events.</p></section></div>
    <section className="resource-next"><div><h2>See the full workflow.</h2><p>Try a sample job, estimate and invoice without creating an account.</p></div><Link className="button" href="/demo">Explore the product tour →</Link></section>
  </main>
}
