import Link from 'next/link'
import { marketingMetadata } from '@/lib/marketing/seo'
import { Breadcrumbs } from '../../_components/breadcrumbs'

export const metadata = marketingMetadata({ title: 'HVAC Software Evaluation Checklist for Small Shops', description: 'Evaluate HVAC software with a real job workflow. Check estimates, invoices, permissions, imports, payment fees, exports and setup before committing.', path: '/resources/hvac-software-checklist', article: true })

const checks = [
  ['Customer and equipment records', 'Create a sample customer with a separate service address. Add equipment details. Find the record from a phone and confirm another customer cannot see it.'],
  ['Estimate and approval', 'Build an estimate with labor and materials. Send it to a test customer address you control. Review it on a phone, approve it, then check that the accepted scope is preserved.'],
  ['Job and team handoff', 'Schedule a sample job and assign a technician. Sign in using a technician account. Confirm that job details are available and owner-only settings are restricted.'],
  ['Invoice and payment status', 'Create the invoice from the estimate, review quantities and tax, and test the supported payment flow using the provider’s test environment. Check failed and delayed payments as well as success.'],
  ['Imports and exports', 'Import a small representative file first. Include a duplicate, missing field and unusual address. Export the records again and check what is included and what needs a separate backup.'],
  ['Connection and device behavior', 'Try your actual phone and browser. Interrupt the connection during a safe test. Check which actions are saved, which are queued and which require you to reconnect.'],
  ['Support and account recovery', 'Find the help center and support address. Try password recovery. Identify who in your business can manage subscriptions and restore access if the owner is unavailable.'],
] as const

export default function ChecklistPage() {
  return <main id="marketing-content" tabIndex={-1} className="section shell">
    <Breadcrumbs items={[{ name: 'Home', path: '/' }, { name: 'Resources', path: '/resources' }, { name: 'Software checklist', path: '/resources/hvac-software-checklist' }]} />
    <header className="page-heading"><p className="eyebrow">A practical buying guide · FieldClose</p><h1>Choose HVAC software<br />by testing the work.</h1><p>A feature list is a starting point. Before committing your shop, run a representative job through the full workflow and record what happens at each handoff.</p></header>
    <div className="resource-editorial"><section><h2>Start with one ordinary job.</h2><p>Pick a recent residential service visit that included a customer, equipment details, an estimate and an invoice. Use clearly labeled sample data in the trial. Set a pass condition for each step: who performs it, what information must survive and what the customer should receive.</p><p>Compare tools using the same scenario. A successful demo is useful; a completed workflow with your own team is stronger evidence of fit.</p></section>
    <section><h2>Your evaluation worksheet</h2><p>For each check, record “passed,” “needs setup,” or “not supported,” plus an owner and next step. Repeat failed checks after configuration changes.</p><div className="resource-table-wrap"><table className="resource-table"><caption>Seven checks for a small HVAC service business</caption><thead><tr><th scope="col">Area</th><th scope="col">What to test</th></tr></thead><tbody>{checks.map(([title, description]) => <tr key={title}><th scope="row">{title}</th><td>{description}</td></tr>)}</tbody></table></div></section>
    <section><h2>Compare the full monthly cost.</h2><p>List the subscription, extra seats, payment processing, platform transaction fees, messaging, storage, add-ons, implementation and any minimum commitment. Ask which charges vary with use and which can be capped. A low starting subscription does not describe the full bill.</p><p>FieldClose lists its current plans on the <Link href="/pricing">pricing page</Link>. Payment processing and applicable platform fees are separate. Review the final subscription and payment terms in your account before paying.</p></section>
    <section><h2>Know the boundaries before you move.</h2><p>Decide which features are required on day one. For FieldClose, customer checkout currently covers the full invoice rather than a partial or deposit checkout. There is no direct QuickBooks or Xero sync, and the web app is not fully offline. Read the <Link href="/help">help center</Link> for current workflow details.</p><p>If your business depends on those features, resolve the gap before rollout. A workaround that is manageable for one technician may become a daily burden for a larger team.</p></section>
    <section><h2>Roll out in a controlled sequence.</h2><ol><li>Keep an export of the original customer and service records.</li><li>Configure business details, roles, service prices and payment settings.</li><li>Validate a small import and compare counts and sample values.</li><li>Complete the workflow checks with the people who will use the app.</li><li>Assign someone to review failed payments, undelivered messages and support issues.</li><li>Move the remaining records only after the first jobs reconcile correctly.</li></ol><p>Use the <Link href="/help/getting-started">FieldClose setup guide</Link> for product-specific steps. Keep your original records accessible until the migration is verified.</p></section></div>
    <section className="resource-next"><div><h2>Try the workflow yourself.</h2><p>The FieldClose tour uses sample data and requires no account.</p></div><Link className="button" href="/demo">Open product tour →</Link></section>
  </main>
}
