-- AlterTable
ALTER TABLE "WebhookEvent" ADD COLUMN "status" TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE "WebhookEvent" ADD COLUMN "attempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "WebhookEvent" ADD COLUMN "lastError" TEXT;
ALTER TABLE "WebhookEvent" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
