import Link from 'next/link'
import { marketingMetadata } from '@/lib/marketing/seo'
import { Breadcrumbs } from '../../_components/breadcrumbs'
import { DocumentTemplate } from '../document-template'

export const metadata = marketingMetadata({ title: 'Free HVAC Estimate Template — Print or Save PDF', description: 'Prepare an HVAC estimate with itemized labor and materials, scope, exclusions and approval terms. Free browser template with printable PDF output. No signup.', path: '/resources/hvac-estimate-template' })

export default function EstimateTemplatePage() {
  return <main id="marketing-content" tabIndex={-1} className="section shell">
    <Breadcrumbs items={[{ name: 'Home', path: '/' }, { name: 'Resources', path: '/resources' }, { name: 'HVAC estimate template', path: '/resources/hvac-estimate-template' }]} />
    <header className="page-heading"><p className="eyebrow">Free printable template</p><h1>A clearer HVAC<br />estimate starts here.</h1><p>Put the scope, line items and approval details in one document. Use this free template for a proposed service or repair, then print or save a PDF.</p></header>
    <DocumentTemplate kind="estimate" />
    <div className="resource-editorial"><section><h2>Write the scope before the total.</h2><p>An HVAC estimate should tell the customer what they are agreeing to. Record the service address and relevant equipment, explain the problem being addressed, and describe the proposed work in plain language.</p><ol><li><strong>Included work:</strong> specify the labor, equipment or parts you propose to provide. Use model numbers where a particular product matters.</li><li><strong>Assumptions and exclusions:</strong> identify work that requires a separate assessment or approval. Do not leave access, electrical changes, disposal or permit arrangements ambiguous when they are relevant.</li><li><strong>Price details:</strong> show quantities, unit prices and applicable tax. Distinguish a firm quoted amount from an allowance that may change.</li><li><strong>Schedule and validity:</strong> include how long the estimate remains valid and any dependencies such as parts availability.</li><li><strong>Acceptance and changes:</strong> explain how the customer approves the work and how you will agree to a revised scope.</li></ol></section>
    <section><h2>Check the price against your costs.</h2><p>A selling price should account for more than the part on the invoice. Calculate the direct material and burdened labor costs, review the overhead assigned to the job, and check what remains at the proposed selling price.</p><p>The <Link href="/tools/hvac-job-pricing-calculator">HVAC job pricing calculator</Link> shows the difference between margin and markup and checks a break-even floor. It uses your inputs rather than prescribing a standard rate.</p></section>
    <section><h2>Keep an approved copy.</h2><p>Give each estimate a unique reference. If you revise it, clearly identify the revision and retain the version the customer approved. This printable template has a signature line, but it does not collect an electronic signature, deliver the document or track acceptance.</p><p>FieldClose’s <Link href="/hvac-estimating-software">HVAC estimating software</Link> supports a connected approval workflow. You can review line items, share the estimate in the customer portal and create a draft invoice from the accepted estimate.</p></section>
    <section><h2>What happens after the job?</h2><p>Confirm the completed scope and any approved changes, then prepare the invoice. You can use the <Link href="/resources/hvac-invoice-template">free HVAC invoice template</Link> for a standalone document. Keep a separate payment record; a PDF does not confirm that money has been received.</p><p>This is a general document aid. Add the contract terms, notices and approval details required for your business and location before using it with customers.</p></section></div>
    <section className="resource-next"><div><h2>From estimate to invoice.</h2><p>See the connected steps with sample data in the public product tour.</p></div><Link className="button" href="/demo">Try the product tour →</Link></section>
  </main>
}
