import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ admin: vi.fn(), find: vi.fn(), update: vi.fn(), transaction: vi.fn(), updateMany: vi.fn(), stripe: vi.fn(), create: vi.fn(), retrieve: vi.fn(), link: vi.fn(), event: vi.fn(), audit: vi.fn() }))
vi.mock('@/lib/require-admin', () => ({ requireAdmin: mocks.admin }))
vi.mock('@/lib/db', () => ({ db: { organization: { findUnique: mocks.find, update: mocks.update, updateMany: mocks.updateMany }, $transaction: mocks.transaction } }))
vi.mock('next/cache', () => ({ revalidatePath: vi.fn() }))
vi.mock('@/lib/stripe', () => ({ getStripe: mocks.stripe }))
vi.mock('@/lib/events', () => ({ trackEvent: mocks.event }))
vi.mock('@/lib/audit', () => ({ logAudit: mocks.audit }))
import { startStripeOnboarding, refreshStripeStatus } from '@/app/settings/stripe/actions'

beforeEach(() => {
  vi.resetAllMocks()
  vi.stubEnv('STRIPE_SECRET_KEY', 'sk_live_fixture')
  mocks.admin.mockResolvedValue({ authorized: true, context: { userId: 'owner', organizationId: 'server-org' } })
  mocks.find.mockResolvedValue({ id: 'server-org', stripeConnectedAccountId: 'acct_one', stripeChargesEnabled: false })
  mocks.stripe.mockReturnValue({ accounts: { create: mocks.create, retrieve: mocks.retrieve }, accountLinks: { create: mocks.link } })
  mocks.audit.mockResolvedValue({})
  mocks.event.mockResolvedValue({})
  mocks.updateMany.mockResolvedValue({ count: 1 })
  mocks.transaction.mockImplementation(fn => fn({ organization: { updateMany: mocks.updateMany } }))
})
afterEach(() => { vi.unstubAllEnvs(); vi.restoreAllMocks() })
describe('recoverable customer payment setup failures', () => {
  it('requests card and transfer capabilities without relying on platform defaults, with stable retry identity', async () => {
    mocks.find.mockResolvedValue({ id: 'server-org', stripeConnectedAccountId: null })
    mocks.create.mockResolvedValue({ id: 'acct_new' })
    mocks.link.mockResolvedValue({ url: 'https://connect.stripe.com/fixture' })
    expect((await startStripeOnboarding()).success).toBe(true)
    expect(mocks.create).toHaveBeenCalledWith({ type: 'express', capabilities: { card_payments: { requested: true }, transfers: { requested: true } }, metadata: { organizationId: 'server-org' } }, { idempotencyKey: 'fieldclose-connect:server-org' })
    expect(mocks.updateMany).toHaveBeenCalledWith({ where: { id: 'server-org', stripeConnectedAccountId: null }, data: { stripeConnectedAccountId: 'acct_new' } })
  })
  it('continues the saved account when a concurrent setup wins the database race', async () => {
    mocks.find.mockResolvedValueOnce({ id: 'server-org', stripeConnectedAccountId: null }).mockResolvedValueOnce({ id: 'server-org', stripeConnectedAccountId: 'acct_winner' })
    mocks.create.mockResolvedValue({ id: 'acct_new' })
    mocks.updateMany.mockResolvedValue({ count: 0 })
    mocks.link.mockResolvedValue({ url: 'https://connect.stripe.com/fixture' })
    expect((await startStripeOnboarding()).success).toBe(true)
    expect(mocks.link).toHaveBeenCalledWith(expect.objectContaining({ account: 'acct_winner' }))
    expect(mocks.update).not.toHaveBeenCalled()
  })
  it('returns a safe retry when the provider account could not be saved, without opening an unbound account link', async () => {
    mocks.find.mockResolvedValue({ id: 'server-org', stripeConnectedAccountId: null })
    mocks.create.mockResolvedValue({ id: 'acct_new' })
    mocks.updateMany.mockRejectedValue(new Error('database unavailable'))
    expect(await startStripeOnboarding()).toEqual({ success: false, error: 'Your payment connection could not be saved. Please try again.' })
    expect(mocks.link).not.toHaveBeenCalled()
  })
  it.each([startStripeOnboarding, refreshStripeStatus])('handles missing provider configuration without throwing or recording success', async action => {
    mocks.stripe.mockImplementation(() => { throw new Error('missing provider key') })
    const result = await action()
    expect(result).toMatchObject({ success: false, error: expect.stringContaining('Customer payments are not configured') })
    expect(mocks.update).not.toHaveBeenCalled()
    expect(mocks.event).not.toHaveBeenCalled()
    expect(mocks.audit).not.toHaveBeenCalled()
  })
  it('handles provider account creation failure without exposing raw provider details', async () => {
    mocks.find.mockResolvedValue({ id: 'server-org', stripeConnectedAccountId: null })
    mocks.create.mockRejectedValue(new Error('Invalid API key sk_example_do_not_echo'))
    expect(await startStripeOnboarding()).toEqual({ success: false, error: 'We could not start customer payment setup. Please try again.' })
    expect(mocks.update).not.toHaveBeenCalled()
  })
  it('does not tell a business owner to configure the platform Stripe account', async () => {
    mocks.find.mockResolvedValue({ id: 'server-org', stripeConnectedAccountId: null })
    mocks.create.mockRejectedValue(new Error('Connect is not enabled'))
    expect(await startStripeOnboarding()).toEqual({ success: false, error: 'Online payment connections are not available yet. You can continue setting up the rest of your workspace.' })
  })
  it('returns a retryable result when the onboarding link cannot be created', async () => {
    mocks.link.mockRejectedValue(new Error('provider unreachable'))
    expect(await startStripeOnboarding()).toEqual({ success: false, error: 'We could not open Stripe payment setup. Please try again.' })
    expect(mocks.event).not.toHaveBeenCalled()
  })
  it('does not replace saved capabilities when Stripe status is unavailable', async () => {
    mocks.retrieve.mockRejectedValue(new Error('provider unreachable'))
    expect(await refreshStripeStatus()).toEqual({ success: false, error: 'We could not refresh your Stripe status. Please try again.' })
    expect(mocks.update).not.toHaveBeenCalled()
    expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({ eventType: 'stripe_account_verification_failed', metadata: { mode: 'live', accountId: 'acct_one' } }))
  })
  it('records live account verification with capabilities in the same transaction as the status update', async () => {
    mocks.retrieve.mockResolvedValue({ id: 'acct_one', charges_enabled: true, payouts_enabled: true })
    expect(await refreshStripeStatus()).toEqual({ success: true, chargesEnabled: true, payoutsEnabled: true })
    expect(mocks.updateMany).toHaveBeenCalledWith({ where: { id: 'server-org', stripeConnectedAccountId: 'acct_one' }, data: { stripeChargesEnabled: true, stripePayoutsEnabled: true } })
    expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({ organizationId: 'server-org', eventType: 'stripe_account_verified', metadata: { mode: 'live', accountId: 'acct_one', chargesEnabled: true, payoutsEnabled: true } }), expect.anything())
  })
  it('records test verification as test even when the account allows charges', async () => {
    vi.stubEnv('STRIPE_SECRET_KEY', 'sk_test_fixture')
    mocks.retrieve.mockResolvedValue({ id: 'acct_one', charges_enabled: true, payouts_enabled: true })
    expect((await refreshStripeStatus()).success).toBe(true)
    expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({ eventType: 'stripe_account_verified', metadata: expect.objectContaining({ mode: 'test' }) }), expect.anything())
  })
  it.each(['event', 'audit'] as const)('returns the saved onboarding link when optional %s recording fails', async failure => {
    const logs = vi.spyOn(console, 'error').mockImplementation(() => {})
    mocks.link.mockResolvedValue({ url: 'https://connect.stripe.com/fixture' })
    mocks[failure].mockRejectedValue(new Error('PRIVATE provider or database detail'))
    expect(await startStripeOnboarding()).toEqual({ success: true, url: 'https://connect.stripe.com/fixture' })
    expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({ eventType: 'stripe_connection_started' }))
    expect(logs).toHaveBeenCalledTimes(1)
    expect(JSON.stringify(logs.mock.calls)).not.toContain('PRIVATE')
  })
  it.each(['event', 'audit'] as const)('preserves a committed verification when optional completion %s recording fails', async failure => {
    const logs = vi.spyOn(console, 'error').mockImplementation(() => {})
    mocks.retrieve.mockResolvedValue({ id: 'acct_one', charges_enabled: true, payouts_enabled: true })
    if (failure === 'audit') mocks.audit.mockResolvedValueOnce({}).mockRejectedValueOnce(new Error('PRIVATE account detail'))
    else mocks.event.mockRejectedValue(new Error('PRIVATE account detail'))
    expect(await refreshStripeStatus()).toEqual({ success: true, chargesEnabled: true, payoutsEnabled: true })
    expect(mocks.audit).toHaveBeenNthCalledWith(1, expect.objectContaining({ eventType: 'stripe_account_verified' }), expect.anything())
    expect(mocks.audit).toHaveBeenNthCalledWith(2, expect.objectContaining({ eventType: 'stripe_connection_completed' }))
    expect(logs).toHaveBeenCalledTimes(1)
    expect(JSON.stringify(logs.mock.calls)).not.toContain('PRIVATE')
  })
  it('still fails closed if the required atomic verification audit cannot commit', async () => {
    mocks.retrieve.mockResolvedValue({ id: 'acct_one', charges_enabled: true, payouts_enabled: true })
    mocks.audit.mockRejectedValueOnce(new Error('database failure'))
    expect(await refreshStripeStatus()).toEqual({ success: false, error: 'Your Stripe status could not be saved. Please refresh it again.' })
    expect(mocks.event).not.toHaveBeenCalled()
  })
  it('does not save verification after the organization changes its connected account', async () => {
    mocks.retrieve.mockResolvedValue({ id: 'acct_one', charges_enabled: true, payouts_enabled: true })
    mocks.updateMany.mockResolvedValue({ count: 0 })
    expect((await refreshStripeStatus()).success).toBe(false)
    expect(mocks.audit).not.toHaveBeenCalled()
  })
})
